project:
  type: website
  output-dir: docs

website:
 navbar:
  title: "Maya Kurani"
  left:
    - href: index.qmd
      text: Home
    - about.qmd
    - projects.qmd
    - photos.qmd

format:
  html:
    theme: styles.scss
    mainfont: Roboto
    toc: true
    page-layout: full

editor: visual

