project:
  type: website
  output-dir: docs

website:
 navbar:
  title: "Maya Kurani" 
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    page-layout: full

editor: visual

